- name: Create physical volume
  command: pvcreate /dev/sda3 && vgextend C3D-SCP-vg /dev/sda3 && lvextend -L+160G /dev/C3D-SCP-vg/root
  become: true
  become_user: 'root'
  ignore_errors: false
- name: Resize partition
  command: resize2fs -p /dev/C3D-SCP-vg/root
  become: true
  become_user: 'root'
  ignore_errors: false