---
name: C3DNA Controller Component For AEM Customers
shortDescription: Application lifecycle management
public: false
author: C3DNA
organization: C3DNA
defaultPlaybook: playbook.yml
imagePath: https://raw.github.com/clc-runner/Assets/master/c3dna.png
description: C3DNA Controller

fields:
- displayName: Datacenter
  name: datacenter
  required: true
  type: datacenters
- displayName: Network
  name: networkID
  parent: datacenter
  required: true
  type: networks
- displayName: Group
  name: groupID
  parent: datacenter
  required: true
  type: groups
- displayName: Server Name
  name: serverName
  required: true
  default: C3DC
  type: text
- displayName: V1 API Key
  name: apiV1Key
  required: true
  type: text
- displayName: V1 API Password
  name: apiV1Passwd
  required: true
  type: text
- displayName: CenturyLink Cloud Username
  name: apiV2User
  required: true
  type: text
- displayName: CenturyLink Cloud Password
  name: apiV2Passwd
  type: text
  required: true
- displayName: Root password for servers
  name: rootPasswd
  type: password
  required: true
  helpText: enter a strong password, a weak one will cause the server build to fail
# - displayName: Unique Controller name
#   name: UUID
#   type: text
#   required: true
#   default: C3DNA_CONTROLLER_MAIN_APPLICATION
