
- name: clear work directory
  file: name=/work state=absent

- name: create work directory
  file: name=/work state=directory mode=0755

- debug:
    var: groupID

- name: give required permissions to rclocal file
  shell: "chmod 744 /etc/rc.local"
  become: true
  become_user: 'root'

- name: copy controller shell file
  template: src=configure_controller.sh dest=/work/configure_controller.sh mode=0755

- name: run controller setup script
  shell: "/work/configure_controller.sh"
  become: true
  become_user: 'root'
  args:
    chdir: /work